if(EXISTS "/home/woo/bustub/build_rel/test/orset_test[1]_tests.cmake")
  include("/home/woo/bustub/build_rel/test/orset_test[1]_tests.cmake")
else()
  add_test(orset_test_NOT_BUILT orset_test_NOT_BUILT)
endif()
