if(EXISTS "/home/woo/bustub/build_rel/test/write_back_cache_test[1]_tests.cmake")
  include("/home/woo/bustub/build_rel/test/write_back_cache_test[1]_tests.cmake")
else()
  add_test(write_back_cache_test_NOT_BUILT write_back_cache_test_NOT_BUILT)
endif()
